2018-11-01 16:32:18.282 [error] <0.1758.0> CRASH REPORT Process <0.1758.0> with 0 neighbours exited with reason: {1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>} in gen_server:init_it/6 line 358
2018-11-01 16:32:18.283 [error] <0.1756.0> Supervisor {<0.1756.0>,ecpool_worker_sup} had child {worker,1} started with ecpool_worker:start_link(emqx_auth_mysql, 1, emqx_auth_mysql_cli, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,3306},{user,[]},{password,[]},{database,...},...]) at undefined exit with reason {1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>} in context start_error
2018-11-01 16:32:18.284 [error] <0.1757.0> CRASH REPORT Process <0.1757.0> with 0 neighbours exited with reason: {1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>} in gen_server:init_it/6 line 358
2018-11-01 16:32:18.287 [error] <0.1754.0> Supervisor {<0.1754.0>,ecpool_pool_sup} had child worker_sup started with ecpool_worker_sup:start_link(emqx_auth_mysql, emqx_auth_mysql_cli, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,3306},{user,[]},{password,[]},{database,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,{worker,1},{1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>}}} in context start_error
2018-11-01 16:32:18.287 [error] <0.1753.0> Supervisor emqx_auth_mysql_sup had child emqx_auth_mysql started with ecpool:start_pool(emqx_auth_mysql, emqx_auth_mysql_cli, [{pool_size,8},{auto_reconnect,1},{host,"127.0.0.1"},{port,3306},{user,[]},{password,[]},{database,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>}}}}} in context start_error
2018-11-01 16:32:18.288 [error] <0.1751.0>@emqx_auth_mysql_app:start:31 CRASH REPORT Process <0.1751.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>}}}}}}}} in emqx_auth_mysql_app:start/2 line 31 in application_master:init/4 line 138
2018-11-01 16:32:18.293 [error] <0.1749.0>@emqx_logger:error:49 Load plugin emqx_auth_mysql error, cannot start app emqx_auth_mysql for {bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{1045,<<"28000">>,<<"Access denied for user ''@'localhost' (using password: NO)">>}}}}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"src/emqx_auth_mysql_app.erl"},{line,31}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}
2018-11-01 16:32:18.293 [error] <0.1749.0> PUT /api/v3/nodes/emqx@127.0.0.1/plugins/emqx_auth_mysql/load error: badarg, stacktrace:
[{jsx_parser,value,4,[{file,"src/jsx_parser.erl"},{line,163}]},{minirest_handler,jsonify,4,[{file,"src/minirest_handler.erl"},{line,130}]},{minirest,handle_request,2,[{file,"src/minirest.erl"},{line,66}]},{minirest,init,2,[{file,"src/minirest.erl"},{line,51}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,274}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,252}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
